rs=int(input("qual o valor da refeição com suco?"))
pp=int(input("qual o valor do prato principal?"))
s=int(input("qual o valor da sobremesa?"))
total=(rs)+(pp)+(s)
print("o valor total da compra é R${:2f}".format(total))
